module.exports = {
  createAdminUser: require('./admin/createAdminUser'),
  deleteAdminUser: require('./admin/deleteAdminUser'),
  getAdminSettings: require('./admin/getAdminSettings'),
  getAnalytics: require('./admin/getAnalytics'),
  getSystemInfo: require('./admin/getSystemInfo'),
  getAccountSettings: require('./admin/getAccountSettings'),
  updateAccountSettings: require('./admin/updateAccountSettings'),
  updateAdminUser: require('./admin/updateAdminUser'),
  downloadDatabaseBackup: require('./admin/downloadDatabaseBackup'),
  listActivityLogs: require('./admin/listActivityLogs'),
  listAdminUsers: require('./admin/listAdminUsers'),
  listRequests: require('./admin/listRequests'),
  updateRequestStatus: require('./admin/updateRequestStatus'),
  updateSettings: require('./admin/updateSettings'),
}
