module.exports = {
  createAdminUser: require('./admin/createAdminUser'),
  createEmployee: require('./admin/employeeDirectory').createEmployee,
  deleteEmployee: require('./admin/employeeDirectory').deleteEmployee,
  importEmployees: require('./admin/employeeDirectory').importEmployees,
  listEmployees: require('./admin/employeeDirectory').listEmployees,
  updateEmployee: require('./admin/employeeDirectory').updateEmployee,
  claimRequest: require('./admin/claimRequest'),
  deleteAdminUser: require('./admin/deleteAdminUser'),
  getAdminSettings: require('./admin/getAdminSettings'),
  getAnalytics: require('./admin/getAnalytics'),
  getSystemInfo: require('./admin/getSystemInfo'),
  getAccountSettings: require('./admin/getAccountSettings'),
  updateAccountSettings: require('./admin/updateAccountSettings'),
  updateAdminUser: require('./admin/updateAdminUser'),
  downloadDatabaseBackup: require('./admin/downloadDatabaseBackup'),
  restoreDatabaseBackup: require('./admin/restoreDatabaseBackup'),
  listActivityLogs: require('./admin/listActivityLogs'),
  listAdminUsers: require('./admin/listAdminUsers'),
  listRequests: require('./admin/listRequests'),
  updateRequestStatus: require('./admin/updateRequestStatus'),
  updateSettings: require('./admin/updateSettings'),
  listBoardRoomBookings: require('./boardRoomController').listBookings,
  deleteBoardRoomBooking: require('./boardRoomController').deleteBooking,
  updateBoardRoomBookingStatus: require('./boardRoomController').updateBookingStatus,
}
